### ISSUE TITLE
Support MAKEOBJDIRPREFIX

### ISSUE THREAD

**Issue by jaycetyle** [jaycetyle/vscode-gnu-global#1]
MAKEOBJDIRPREFIX is an enviroment variable which can be configured. If $MAKEOBJDIRPREFIX directory exists, gtags creates $MAKEOBJDIRPREFIX/<cwd> directory and makes tag files in it. Global will search  $MAKEOBJDIRPREFIX/<cwd> for tag files. We can avoid tag files messing up the project directory.

It seems like that the Windows version of GNU Global doesn't support this option because the paths in Windows have drive prefix (ex: c:/) and GNU Global cannot work with it. Despite this limitation, this feature is still nice to have for Linux users.

**Comment by Schievel1** [comment]
Has anyone got this to work with Windows? It is weird that the windows version does support GTAGSLIBPATH with c:/-Style paths, but not GTAGSOBJDIRPREFIX.

**Comment by Schievel1** [comment]
I looked it up in the source, it would just skip it on windows no matter what you set.

How GTAGSLIBPATH works with windows binary is beyond me, but since it only works in the one distributed from Jason and not in MSYS2 one, it seems he's patching something. 

However, the fix is pretty easy, it's just since global concatenates GTAGSOBJDIRPREFIX and cwd when creating GTAGS/ GPATH/ GRTAGS, it will end up with something like C:/my/path/to/gtagsobjdirprefix/C:/my/cwd at best. C: is not allowed as a dir or filename in Windows. 
I patched the sources from gnu to work with this and remove the :. I will send them a patch. I will also upload the patched code.
